trigger:
  - develop
  

pool:
  #vmImage: "ubuntu-latest"
  name: ADF-Infra-dev

stages:
  - stage: Build
    jobs:
      - job:
        displayName: Build artifacts
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish modules"
            inputs:
              targetPath: "ADF-Infrastructure/terraform"
              artifactName: "ADF-Infrastructure"

  - stage: dev
    jobs:
      - template: ../stages/terraform.yaml
        parameters:
          environment: dev
          connection: SSEU-ETL-CIP-dev
          resourceGroup: RGAZ-SSEU-ETL-CIP-dev
          storageAccount: terraformadf
          adfStorageAccount: northstarstoragedev
