trigger:
  - release
  

pool:
  #vmImage: "ubuntu-latest"
  name: ADF-Infra-uat

stages:
  - stage: Build
    jobs:
      - job:
        displayName: Build artifacts
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish modules"
            inputs:
              targetPath: "ADF-Infrastructure/terraform"
              artifactName: "ADF-Infrastructure"

  
  - stage: UAT
    jobs:
      - template: ../stages/terraform.yaml
        parameters:
          environment: uat
          connection: SSEU-ETL-CIP-UAT
          resourceGroup: RGAZ-SSEU-ETL-CIP-UAT
          storageAccount: terraformadfuat
          adfStorageAccount: northstarstorageacctuat
